In [1]:
import torch
import os
import model as m
import preprocessing as prep
import loading_data as ld
from config import TRAINING_PATH, PREDICTION_PATH

In [2]:
trailer_name_train = '86.Малыш на драйве.mp4'
prep.preprocess(trailer_name_train, train=True, verbose=True)

dir_names = os.listdir(TRAINING_PATH)
dir_names = list(filter(lambda x: os.path.isdir(f"{TRAINING_PATH}/{x}"), dir_names)) #Filtering waste files

X_test, y_test, dir_names = ld.load_data(dir_names, train=True, verbose=True, batch_size=1)

model = m.LRCN()
model.train(dir_names, X_test, y_test, verbose=True)
y = model.predict_single('85.Дикая.mp4', verbose=True)

0 iteration...
....Making subclip....
Moviepy - Running:
>>> "+ " ".join(cmd)
Moviepy - Command successful
....Extracting frames....
Extracting frames from 0.mp4
len VR 833
FRAMES [[[[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  ...

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]]


 [[[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  ...

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   [0 0 0]
   [0 0 0]]

  [[0 0 0]
   [0 0 0]
   [0 0 0]
   ...
   [0 0 0]
   

processing 86.Малыш на драйве_1
File 86.Малыш на драйве is not found in the markup
processing 86.Малыш на драйве_0


TypeError: train() got an unexpected keyword argument 'verbose'